"""added config

Revision ID: 712251184b0d
Revises: 3d68f9316c3a
Create Date: 2026-05-12 16:37:56.938174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712251184b0d'
down_revision: Union[str, Sequence[str], None] = '3d68f9316c3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_verifled',new_column_name='is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verifled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified',new_column_name='is_verifled')
    # ### end Alembic commands ###
