"""added config

Revision ID: 7873fb76dd9c
Revises: 188d65eb66ea
Create Date: 2026-05-12 17:02:02.491042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7873fb76dd9c'
down_revision: Union[str, Sequence[str], None] = '188d65eb66ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_verifled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verifled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
